#!/bin/sh

regex = '@thinkartha\.com$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
  echo your email satisfies git policy
  exit 0
else
  echo your email doesnt satisfy git policy
  exit 1
fi
